spring:
  main:
    banner-mode: off

  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"


mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    jdbc-type-for-null: varchar


logging:
  level:
    root: info
    org.apache.tomcat.util: info


server:
  port: 3724
